version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.5.1-alpine
  bob:
    build: .
    image: bob:latest
    command: ruby init.rb
    volumes:
      - ./:/app
    depends_on:
      - elasticsearch
